version: '3'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: test
      DB_HOST: db

  server:
    build:
      context: ./server
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    build:
      context: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test