version: "3"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: test
      DB_HOST: db
    networks:
      - pern-network

  server:
    build:
      context: ./server
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PGUSER=${POSTGRES_USER}
    networks:
      - pern-network

  db:
    build:
      context: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      PGUSER: "postgres"
    healthcheck:
      #CHANGE 1: this command checks if the database is ready, right on the source db server
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pern-network

networks:
  pern-network:
    driver: bridge
