# Use an official PostgreSQL image as a parent image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB=perntodo \
    POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=test

# Expose the default PostgreSQL port
EXPOSE 5432